name: Feature Branch CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"

    - name: Run Flake8 Lint
      run: |
        flake8
    
    - name: Run Pytest
      run: |
        pytest
